/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimo;

import Exemplar.Exemplar;
import Exemplar.ExemplarDAO;
import Operador.Login;
import Operador.Operador;
import Usuario.TelaUsuarioEmprestimo;
import Usuario.Usuario;
import static bibliotecacad.Principal.jDesktopPanePrincipal;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Ana PAtrícia
 */
public class TelaEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TeaEmprestimo
     */
    JTextField usuarioEmprestimo1  = new JTextField();
    JPasswordField senhaUsuarioEmprestimo = new JPasswordField();
    JTextField operadorEmprestimo1 = new JTextField();
    JPasswordField senhaoperadorEmprestimo = new JPasswordField();
    
    public TelaEmprestimo() throws SQLException {
        initComponents();
        usuarioEmprestimo1.setText(TelaUsuarioEmprestimo.nomeUsuario.getText());
        senhaUsuarioEmprestimo.setText(TelaUsuarioEmprestimo.senha.getText()); 
        
        Usuario usuario = new Usuario();
        usuario.setNomeUsuario(usuarioEmprestimo1.getText());
        usuario.setSenha(senhaUsuarioEmprestimo.getText());
        
        Usuario usuario1 = usuario.selecionarUsuario(usuario);
        String nome = usuario1.getNomeCompleto();
        usuarioEmprestimo.setText(nome);
        operadorEmprestimo.setText(Login.nomeOperador.getText());
    }
     public void TelaUsuarioEmprestimo(){
        TelaUsuarioEmprestimo telaUsuarioEmprestimo = new TelaUsuarioEmprestimo();
        jDesktopPanePrincipal.add(telaUsuarioEmprestimo);
        telaUsuarioEmprestimo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        dadosLivro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalhes = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        exemplar1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioEmprestimo = new javax.swing.JTextField();
        operadorEmprestimo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setTitle("Empréstimo");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Confirmar Empréstimo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dadosLivro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes do Exemplar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextAreaDetalhes.setColumns(20);
        jTextAreaDetalhes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextAreaDetalhes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetalhes);

        javax.swing.GroupLayout dadosLivroLayout = new javax.swing.GroupLayout(dadosLivro);
        dadosLivro.setLayout(dadosLivroLayout);
        dadosLivroLayout.setHorizontalGroup(
            dadosLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        dadosLivroLayout.setVerticalGroup(
            dadosLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        exemplar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exemplar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exemplar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Exemplar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Operador");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuário");

        usuarioEmprestimo.setEditable(false);
        usuarioEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuarioEmprestimo.setEnabled(false);

        operadorEmprestimo.setEditable(false);
        operadorEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        operadorEmprestimo.setEnabled(false);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exemplar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1))
                            .addComponent(usuarioEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(operadorEmprestimo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dadosLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton3))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operadorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exemplar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(340, 100, 702, 418);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        DetalhesExemplar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VerificarStatus();
    }//GEN-LAST:event_jButton2ActionPerformed
    /*Impreime em um JTextArea os detalhes do exemplar a ser emprestado*/
    private void DetalhesExemplar(){
        Exemplar exemplar = new Exemplar();
        exemplar.setCodigoExemplar(exemplar1.getText());
        ExemplarDAO exemplarDAO = new ExemplarDAO();
        Detalhes detalhes = new Detalhes();
        try {
            detalhes = exemplarDAO.DetalhesExemplar(exemplar);
        } catch (SQLException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextAreaDetalhes.setText(detalhes.toString());
    }
    /*Chama o método que seleciona um exemplar para verificar qual seu status*/
    private void VerificarStatus(){
        ExemplarDAO exemplarDAO = new ExemplarDAO();
        Exemplar exemplar = new Exemplar();
        exemplar.setCodigoExemplar(exemplar1.getText());
        try {
            exemplar = exemplarDAO.selecionarStatusExemplar(exemplar.getCodigoExemplar());
        } catch (SQLException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!"emprestado".equals(exemplar.getStatus())){
            confirmarEmprestimo();
        }else {
            JOptionPane.showMessageDialog(null, "Exemplar emprestado!");
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FecharTelaEmprestimo();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exemplar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exemplar1ActionPerformed
        // TODO add your handling code here:
        DetalhesExemplar();
    }//GEN-LAST:event_exemplar1ActionPerformed
   /*Confirma um emprestimo, chamando os métodos necessários e o método que o direciona para ser salvo no 
    banco de dados da aplicacao*/
    public void confirmarEmprestimo(){
        //A variáveis globais do tipo JtextField recebem o usuario e senha informados
        usuarioEmprestimo1.setText(TelaUsuarioEmprestimo.nomeUsuario.getText());
        senhaUsuarioEmprestimo.setText(TelaUsuarioEmprestimo.senha.getText());
        TelaUsuarioEmprestimo telaUsuarioEmprestimo1 = new TelaUsuarioEmprestimo();
        Usuario usuario = new Usuario();
        //O usuario recebe os dados informados
        usuario.setNomeUsuario(usuarioEmprestimo1.getText());
        usuario.setSenha(senhaUsuarioEmprestimo.getText());
        System.out.println(usuario);
        Usuario usuario1;
        //O usario é direcionado para autenticação
        usuario1 = telaUsuarioEmprestimo1.autenticar(usuario);
        Usuario usuario2 = new Usuario();
        
        try {
            //Os dados do usuario são buscados no banco de dados
            usuario2 = usuario.selecionarUsuario(usuario1);
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //A variáveis globais do tipo JtextField recebem o usuario e senha do operador informados
        operadorEmprestimo1.setText(Login.nomeOperador.getText());
        senhaoperadorEmprestimo.setText(Login.passwordOperador.getText());
        Operador operador = new Operador();
        //O operador recebe os dados informados
        operador.setNomeOperador(operadorEmprestimo1.getText());
        operador.setSenha(senhaoperadorEmprestimo.getText());
        Operador operador1 = new Operador();
        try {
            //Os dados do operador são buscados no banco de dados
            operador1 = operador.buscarOperador(operador);
        } catch (SQLException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //o emprestimo recebe os dados do usurio e operador buscados e o exemplar informado
        Emprestimo emprestimo = new Emprestimo();
        Exemplar exemplar = new Exemplar();
        exemplar.setCodigoExemplar(exemplar1.getText());
        emprestimo.setExemplar(exemplar);
        emprestimo.setOperador(operador1);
        emprestimo.setUsuario(usuario2);
        //O emprestmo recebe a data do sistema 
        emprestimo.setDataEmprestimo(Calendar.getInstance().getTime());
        //operação para se obter a data prevista para devolucao
        //a data prevista recebe a data do emprestimo e soma à quantidade de dias de emprestimo do usuario
        int diasEmprestimo = 0;
        try {
            //Busca a quantidade de dias do emprestimo de acordo com o tipo de usuario
            diasEmprestimo = emprestimo.returnQuantidadeDiasEmprestimo(usuario1.getNomeUsuario(), usuario1.getSenha());
        } catch (SQLException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //A variavel recebe a data do emprestimo mais a quantidade de dias do emprestimo
        int date = emprestimo.getDataEmprestimo().getDate() + diasEmprestimo;
        Date dataPrevista;
         
        dataPrevista = Calendar.getInstance().getTime();
        //A variável recebe a data prevista
        dataPrevista.setDate(date);
        emprestimo.setDataPrevistaDevolucao(dataPrevista);
        try {
            //O emprestimo é salvo
            emprestimo.salvar(emprestimo);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(TelaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        } 
        System.out.println(emprestimo.getDataEmprestimo());
        System.out.println(emprestimo.getDataPrevistaDevolucao());
  }
  public void FecharTelaEmprestimo() {
        this.dispose();
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dadosLivro;
    private javax.swing.JTextField exemplar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDetalhes;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField operadorEmprestimo;
    private javax.swing.JTextField usuarioEmprestimo;
    // End of variables declaration//GEN-END:variables
}

